### ISSUE TITLE
Error: No matching export in "node_modules/react-native-web/dist/index.js" for import "TurboModuleRegistry"

### ISSUE THREAD

**Issue by bpotaczek** [DataDog/dd-sdk-reactnative#518]
**Describe what happened**

Starting getting this error when we updated the library version from 1.7.0 -> 1.8.* 

```
Your configFile threw an error from: cypress.config.js

We stopped running your tests because your config file crashed.

Error: Build failed with 4 errors:
node_modules/@datadog/mobile-react-native/lib/module/specs/NativeDdLogs.js:8:9: ERROR: No matching export in "node_modules/react-native-web/dist/index.js" for import "TurboModuleRegistry"
node_modules/@datadog/mobile-react-native/lib/module/specs/NativeDdRum.js:8:9: ERROR: No matching export in "node_modules/react-native-web/dist/index.js" for import "TurboModuleRegistry"
node_modules/@datadog/mobile-react-native/lib/module/specs/NativeDdSdk.js:8:9: ERROR: No matching export in "node_modules/react-native-web/dist/index.js" for import "TurboModuleRegistry"
node_modules/@datadog/mobile-react-native/lib/module/specs/NativeDdTrace.js:8:9: ERROR: No matching export in "node_modules/react-native-web/dist/index.js" for import "TurboModuleRegistry"
    at failureErrorWithLog (/Users/runner/work/1/s/node_modules/vite/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/runner/work/1/s/node_modules/vite/node_modules/esbuild/lib/main.js:1058:25
    at /Users/runner/work/1/s/node_modules/vite/node_modules/esbuild/lib/main.js:1525:9
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

vite.config.ts
```
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { viteCommonjs, esbuildCommonjs } from '@originjs/vite-plugin-commonjs';

// https://vitejs.dev/config/
export default defineConfig({
  define: {
    global: 'window',
  },
  optimizeDeps: {
    include: ['@react-navigation/native'],
    esbuildOptions: {
      mainFields: ['module', 'main'],
      resolveExtensions: ['.web.js', '.js', '.ts'],
      plugins: [esbuildCommonjs(['@react-navigation/elements'])],
      loader: {
        '.js': 'jsx',
      },
    },
  },
  resolve: {
    extensions: ['.web.tsx', '.web.jsx', '.web.js', '.tsx', '.ts', '.js'],
    alias: {
      'react-native': 'react-native-web',
    },
    preserveSymlinks: true
  },
  plugins: [viteCommonjs(), react()],
  build: {
    commonjsOptions: {
      transformMixedEsModules: true,
    },
  },
  esbuild: {
    loader: 'tsx',
    include: [
      'src/**/*.jsx',
      'src/**/*.tsx',
      'cypress/**/*.tsx',

      'node_modules/**/*.jsx',
      'node_modules/**/*.tsx',

      'src/**/*.js',
      // "node_modules/**/*.js",

      'src/**/*.ts',
      'node_modules/**/*.ts',
    ],
    exclude: [],
  },
});

```

package.json
```
{
  "name": "com.endotronix.cordella.onthego",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "lint": "eslint .",
    "start": "react-native start",
    "test": "cypress run -b 'chrome' --component --reporter 'junit'",
    "pods:install": "cd ios && bundle exec pod install && cd ..",
    "pods:clean": "cd ios && bundle exec pod deintegrate && cd ..",
    "pods:reinstall": "yarn pods:clean && yarn pods:install",
    "prepare": "husky install",
    "android:staging": "react-native run-android --variant=stagingdebug",
    "android:staging-release": "react-native run-android --variant=stagingrelease",
    "android:dev": "react-native run-android --variant=developmentdebug",
    "android:dev-release": "react-native run-android --variant=developmentrelease",
    "android:prod": "react-native run-android --variant=productiondebug",
    "android:prod-release": "react-native run-android --variant=productionrelease",
    "ios:dev": "react-native run-ios --scheme 'TestAppDevelopment'",
    "ios:prod": "react-native run-ios --scheme 'TestAppProduction'",
    "ios:staging": "react-native run-ios --scheme 'TestAppStaging'"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{js,ts,tsx}": [
      "prettier --write",
      "eslint --fix",
      "git add"
    ],
    "*.{html,css,less,ejs}": [
      "prettier --write",
      "git add"
    ]
  },
  "dependencies": {
    "@datadog/mobile-react-native": "^1.6.0",
    "@datadog/mobile-react-navigation": "^1.6.0",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@reduxjs/toolkit": "^1.9.3",
    "babel-plugin-module-resolver": "^5.0.0",
    "react": "18.2.0",
    "react-dom": "^18.2.0",
    "react-is": "^18.2.0",
    "react-native": "0.71.6",
    "react-native-auth0": "^2.17.2",
    "react-native-config": "^1.5.1",
    "react-native-paper": "^5.6.0",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-svg": "^13.9.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-typescript-transformer": "^1.2.13",
    "react-native-vector-icons": "9.2.0",
    "react-native-web": "0.19.5",
    "react-redux": "^8.0.5",
    "redux-logger": "^3.0.6"
  },
  "devDependencies": {
    "@babel/core": "^7.21.4",
    "@babel/preset-env": "^7.21.4",
    "@babel/preset-typescript": "^7.21.4",
    "@babel/runtime": "^7.20.0",
    "@originjs/vite-plugin-commonjs": "^1.0.3",
    "@react-native-community/eslint-config": "^3.2.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/node": "^18.15.11",
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.4",
    "@types/react-native": "^0.71.6",
    "@types/react-native-auth0": "^2.17.4",
    "@types/react-native-vector-icons": "^6.4.13",
    "@types/redux-logger": "^3.0.9",
    "@vitejs/plugin-react": "^4.0.0",
    "cypress": "12.12.0",
    "eslint": "^8.19.0",
    "eslint-config-prettier": "^8.8.0",
    "husky": "^8.0.0",
    "jetifier": "^2.0.0",
    "lint-staged": "^13.2.2",
    "prettier": "^2.4.1",
    "react-native-clean-project": "^4.0.1",
    "react-test-renderer": "^18.2.0",
    "typescript": "^4.9.5",
    "vite": "^4.3.6"
  }
}

```

Running `yarn test` fails now anytime after using 1.8.*

**Describe what you expected:**

Expect the tests to pass.

**Additional context**

-   Version of the SDK: 1.8.*
-   Version of React Native: 0.71.6

**Comment by louiszawadzki** [comment]
Hi @bpotaczek, thanks for reaching out and sorry for the delay!

From what I understand you are using `@datadog/mobile-react-native` with `react-native-web`, is that correct?
If so, we don't officially support `react-native-web` usage yet (it's on our roadmap), so you probably have some bindings somewhere in your code to make it work that were broken by our upgrade to support the new RN architecture in 1.8.0.

If you can share the code where you make `@datadog/mobile-react-native` compatible with `react-native-web` I can try to help you fix it.

Let us now if your use case is different so we can help troubleshoot it.

Thanks a lot!

**Comment by louiszawadzki** [comment]
Hi @bpotaczek,

There has not been any activity on this issue for a while so I'm going to close it.

Feel free to reopen it with more details if you still encounter the problem :)
