### ISSUE TITLE
Can't compile on RN 0.73 with new arch enabled due to `Too many arguments for public constructor DdRum, DdSdk, DdLogs`

### ISSUE THREAD

**Issue by remacr** [DataDog/dd-sdk-reactnative#648]
### Describe the bug

I can't compile the project because the SDK has a compilation error in `@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/DdSdkReactNativePackage.kt`

### Reproduction steps

`package.json`
```json
{
  "react": "18.2.0",
  "react-native": "0.73.6",
   "@datadog/mobile-react-native": "2.3.1", 
   "@datadog/mobile-react-native-code-push": "2.3.1",
   "@datadog/mobile-react-navigation": "2.3.1",
}
```

<img width="1667" alt="Screenshot 2024-04-05 at 4 28 51 PM" src="https://github.com/DataDog/dd-sdk-reactnative/assets/30184031/67b5e6f8-8554-4401-8aba-e955982cf2ce">

If I manually remove the extra argument in the 3 constructors, I can continue with the compilation without issues.

```diff
diff --git a/node_modules/@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/DdSdkReactNativePackage.kt b/node_modules/@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/DdSdkReactNativePackage.kt
index 8fcf84a..0d32b60 100644
--- a/node_modules/@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/DdSdkReactNativePackage.kt
+++ b/node_modules/@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/DdSdkReactNativePackage.kt
@@ -20,10 +20,10 @@ class DdSdkReactNativePackage : TurboReactPackage() {

     override fun getModule(name: String, reactContext: ReactApplicationContext): NativeModule? {
         return when (name) {
-            DdSdkImplementation.NAME -> DdSdk(reactContext, sdkWrapper)
-            DdRumImplementation.NAME -> DdRum(reactContext, sdkWrapper)
+            DdSdkImplementation.NAME -> DdSdk(reactContext)
+            DdRumImplementation.NAME -> DdRum(reactContext)
             DdTraceImplementation.NAME -> DdTrace(reactContext)
-            DdLogsImplementation.NAME -> DdLogs(reactContext, sdkWrapper)
+            DdLogsImplementation.NAME -> DdLogs(reactContext)
             else -> null
         }
     }
 
```

### SDK logs

```
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
e: file:///my-project/node_modules/@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/DdSdkReactNativePackage.kt:23:61 Too many arguments for public constructor DdSdk(reactContext: ReactApplicationContext) defined in com.datadog.reactnative.DdSdk

e: file:///my-project/node_modules/@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/DdSdkReactNativePackage.kt:24:61 Too many arguments for public constructor DdRum(reactContext: ReactApplicationContext) defined in com.datadog.reactnative.DdRum

e: file:///my-project/node_modules/@datadog/mobile-react-native/android/src/main/kotlin/com/datadog/reactnative/DdSdkReactNativePackage.kt:26:63 Too many arguments for public constructor DdLogs(reactContext: ReactApplicationContext) defined in com.datadog.reactnative.DdLogs FAILURE: Build 
failed with an exception. * What went wrong:
Execution failed for task ':datadog_mobile-react-native:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error. See log for more details * Try:
```

### Expected behavior

The project was built successfully.

### Affected SDK versions

2.3.1

### Latest working SDK version

N/A

### Did you confirm if the latest SDK version fixes the bug?

No

### Integration Methods

Yarn

### React Native Version

0.73.6

### Package.json Contents

{
  "react": "18.2.0",
  "react-native": "0.73.6",
   "@datadog/mobile-react-native": "2.3.1", 
   "@datadog/mobile-react-native-code-push": "2.3.1",
   "@datadog/mobile-react-navigation": "2.3.1",
}

### iOS Setup

N/A

**Comment by marco-saia-datadog** [comment]
Hi @remacr, thanks for reaching out! 

There seems to be a problem with some changes that were introduced in the recent v2.3.0. I will open a PR to address this issue and I will keep you in the loop. 

The safest course of action is to downgrade momentarily to v2.2.0, and follow the progress on the PR that I will post here.

Alternatively, for testing purposes, you could use [patch-package](https://www.npmjs.com/package/patch-package) and easily create a patch with the diff you have provided, in order to remove the extra argument in the 3 constructors.

**Comment by remacr** [comment]
@marco-saia-datadog I did use `patch-package` to avoid downgrading and continue since it was a small change, I took the diff I posted from that tool. Thanks for taking care of the issue.

**Comment by marco-saia-datadog** [comment]
Hey @remacr, I am glad to inform you that we have released [v2.3.3](https://github.com/DataDog/dd-sdk-reactnative/releases/tag/2.3.3) which fixes the new architecture compilation issue with PR #654!
