### ISSUE TITLE
Compilation errors when migrating from 1.0.0 to 1.1.0 on iOS

### ISSUE THREAD

**Issue by diego-paired** [DataDog/dd-sdk-reactnative#263]
After updating the library from version 1 to 1.1, our application will not compile on iOS anymore, with the following error:
```
▸ Compiling DdSdkConfiguration.swift

❌  /Users/a/Code/GitHub/better-half-app/node_modules/@datadog/mobile-react-native/ios/Sources/DdLogs.swift:10:11: 'Logger' is ambiguous for type lookup in this context

extension Logger: NativeLogger { }
             ^


▸ Compiling QueueHolder.swift
▸ Compiling DdLogs.swift

❌  /Users/a/Code/GitHub/better-half-app/node_modules/@datadog/mobile-react-native/ios/Sources/DdLogs.swift:10:11: 'Logger' is ambiguous for type lookup in this context

extension Logger: NativeLogger { }
              ^



❌  /Users/a/Code/GitHub/better-half-app/node_modules/@datadog/mobile-react-native/ios/Sources/DdLogs.swift:40:29: cannot convert value of type 'Logger' to closure result type 'NativeLogger'

        self.init { builder.build() }
              ^


▸ Compiling DdRum.swift

❌  /Users/a/Code/GitHub/better-half-app/node_modules/@datadog/mobile-react-native/ios/Sources/DdLogs.swift:10:11: 'Logger' is ambiguous for type lookup in this context

extension Logger: NativeLogger { }
                    ~~~~~~~~^~~~~~~



❌  /Users/a/Code/GitHub/better-half-app/node_modules/@datadog/mobile-react-native/ios/Sources/DdLogs.swift:40:29: cannot convert value of type 'Logger' to closure result type 'NativeLogger'

        self.init { builder.build() }
              ^



⚠️  /Users/a/Library/Developer/Xcode/DerivedData/Paired-gsjchqvolhsqdifsvjukqihmgyjp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/DatadogSDKReactNative.build/Objects-normal/arm64/DdRum-f8a38bfcf806e72a92f72f0dc8d811bf.dia:1:1: Could not read serialized diagnostics file: error("Invalid diagnostics signature") (in target 'DatadogSDKReactNative' from project 'Pods')

Command CompileSwift failed with a nonzero exit code
                    ~~~~~~~~^~~~~~~


▸ Compiling RNDdSdkConfiguration.swift

❌  error: emit-module command failed with exit code 1 (use -v to see invocation)

```

```
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 109.38 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 27, 28, 29, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.0.0, 33.0.0, 33.0.0
      System Images: android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Chipmunk 2021.2.1 Patch 2 Chipmunk 2021.2.1 Patch 2
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /Users/diegolopez/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: ^9.0.0 => 9.1.0
    react: ^18.2.0 => 18.2.0
    react-native: ^0.69.5 => 0.69.5
    react-native-macos: Not Found
  npmGlobalPackages:
```

**Comment by louiszawadzki** [comment]
Hi @diego-paired, thanks for reaching out!
This looks similar to this issue reported yesterday: https://github.com/DataDog/dd-sdk-reactnative/issues/262

Could you share your `Podfile` to help us troubleshoot? 

Thanks a lot!

**Comment by diego-paired** [comment]
Thanks for your reply. 
We're not using `use_frameworks!` AFAIK

```
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
source 'https://github.com/CocoaPods/Specs.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "1"

pod 'ZendeskCommonUISDK', '6.1.1'
pod 'ZendeskMessagingAPISDK', '3.8.2'
pod 'ZendeskMessagingSDK', '3.8.2'
pod 'ZendeskSDKConfigurationsSDK', '1.1.8'

target 'Redacted' do
  use_expo_modules!
  config = use_native_modules!
  
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :production => production,
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # User added
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true

  # Permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"


  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

# OneSignal https://documentation.onesignal.com/docs/react-native-sdk-setup#step-4---install-for-ios-using-cocoapods-for-ios-apps
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
end
```

**Comment by louiszawadzki** [comment]
Hi @diego-paired, thanks for providing this information!

It looks like this error happens with expo builds. 

We've recently created an `expo-datadog` package dedicated for expo (it includes a config plugin to upload your source maps for crash reporting support for Expo 45 - support for Expo 46 is coming soon). This package uses `@datadog/mobile-react-native` at its version `1.0.0`, so you can use it if you want a version that is going to be more stable for Expo.

If you want to use version `1.1.0` of `@datadog/mobile-react-native`, you should be able to do so by modifying `node_modules/@datadog/mobile-react-native/ios/Sources/DdLogs.swift` and changing `Logger` in line 10 to `DDLogger`. You might need to re-install your Pods afterwards.

Tell me if this works for you, if so I will be releasing `1.1.1` with the `DDLogger` change early next week.
Thanks!

**Comment by diego-paired** [comment]
@louiszawadzki thanks, we'll wait for the release next week.
